// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3BDOyyafULS6Oz0lC1g2G5Nm2Cij5Rb8',
    appId: '1:650505206929:web:f376d88253c0b25b50d330',
    messagingSenderId: '650505206929',
    projectId: 'finledger-8c24a',
    authDomain: 'finledger-8c24a.firebaseapp.com',
    storageBucket: 'finledger-8c24a.firebasestorage.app',
    measurementId: 'G-VCH0MZ3FFZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl_bbMyn-42baR1leOPcnkLvRm2dnFlpA',
    appId: '1:650505206929:android:ef4cd3dc011df68050d330',
    messagingSenderId: '650505206929',
    projectId: 'finledger-8c24a',
    storageBucket: 'finledger-8c24a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtt6XNK5oeDwhl7CF8QPsKEaEwu31cSBA',
    appId: '1:650505206929:ios:b08334d624fcd28150d330',
    messagingSenderId: '650505206929',
    projectId: 'finledger-8c24a',
    storageBucket: 'finledger-8c24a.firebasestorage.app',
    iosBundleId: 'com.vhx.finledger',
  );
}
